version: 0.6.1.{build}
skip_commits:
  files:
    - README.md
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
environment:
    _VERSION: '%APPVEYOR_BUILD_VERSION%-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT:~0,8%'
    _VERSION2: '%APPVEYOR_BUILD_VERSION:.=,%'
    _ZIPFILE: '%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%_v%_VERSION%_%PLATFORM%.zip'
build_script:
- cmd: >-
    msbuild "%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%.sln" /verbosity:minimal /logger:"%PROGRAMFILES%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:_VERSION="%_VERSION%" /p:_VERSION2="%_VERSION2%"

after_build:
- cmd: >-

    copy /Y "COPYING.txt" "install\"

    cd "%APPVEYOR_BUILD_FOLDER%\install"
    
    for /R %%G in (*.bat) do unix2dos "%%G"
    
    7z a "%_ZIPFILE%" "..\install"
    
    7z rn "%_ZIPFILE%" "install" "%APPVEYOR_PROJECT_NAME%"

artifacts:
- path: '*.zip'
