version: 0.6.1.{build}
skip_commits:
  files:
    - README.md
    - CONTRIBUTING.md
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
build:
  verbosity: minimal
before_build:
- cmd: >-
    set "BUILD_VERSION=%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT:~0,8%"

    set "BUILD_VERSION_COMMA_SEP=%APPVEYOR_BUILD_VERSION:.=,%"

    set "BUILD_ZIPFILE=%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%_v%BUILD_VERSION%_%PLATFORM%.zip"

after_build:
- cmd: >-
    copy /Y "LICENSE" "install\COPYING.txt"
    
    cd "%APPVEYOR_BUILD_FOLDER%\install"
    
    for /R %%G in (*.bat) do unix2dos "%%G"
    
    7z a "%BUILD_ZIPFILE%" "..\install"
    
    7z rn "%BUILD_ZIPFILE%" "install" "%APPVEYOR_PROJECT_NAME%"

artifacts:
- path: '*.zip'
